export const GET_ALL_PLANTS = 'GET_ALL_PLANTS';
export const POST_PLANT = 'POST_PLANT';
export const DELETE_PLANT = 'DELETE_PLANT';
export const GET_PLANTS_BY_TYPE = 'GET_PLANTS_BY_TYPE';
export const GET_PLANT_HISTORY_BY_ID = 'GET_PLANT_HISTORY_BY_ID';

//auth
export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL= "AUTH_FAIL";
export const AUTH_LOGOUT="AUTH_LOGOUT";

//Vendor Types
export const GET_ALL_VENDORS = 'GET_ALL_VENDORS';
export const GET_VENDOR_BYID = "GET_VENDOR_BYID";
export const POST_VENDOR = 'POST_VENDOR';
export const DELETE_VENDOR = 'DELETE_VENDOR';

//Azure Loss
export const GET_AZURELOSS = 'GET_AZURELOSS';
export const POST_AZURELOSS = 'POST_AZURELOSS';
export const SEARCH_AZURELOSS = 'SEARCH_AZURELOSS';
export const DELETE_AZURELOSS = 'DELETE_AZURELOSS';
export const CLEAR_AZURELOSS = 'CLEAR_AZURELOSS';

export const SHOW_SPINNER = 'SHOW_SPINNER';
export const HIDE_SPINNER = 'HIDE_SPINNER';
export const SHOW_ALERT = 'SHOW_ALERT';

//Plant Fault Data
export const GET_PLANTFAULT_GEN = 'GET_PLANTFAULT_GEN';
export const GET_PROJECT_TYPE = 'GET_PROJECT_TYPE';
export const GET_PLANT_TYPE = 'GET_PLANT_TYPE';
export const GET_PLANT_FAULT = 'GET_PLANT_FAULT';
export const POST_PLANTFAULT = 'POST_PLANTFAULT';
export const GET_ADD_PLANT_TYPE = 'GET_ADD_PLANT_TYPE';
export const DELETE_PLANT_FAULT = 'DELETE_PLANT_FAULT';
export const SEARCH_PLANT_FAULT_DATA = 'SEARCH_PLANT_FAULT_DATA';
export const CLEAR_PLANT_FAULT = 'CLEAR_PLANT_FAULT';
export const GET_PLANT_AVALIABILITY_FOR_PLANTID = 'GET_PLANT_AVALIABILITY_FOR_PLANTID';
export const POST_PLANTFAULT_INCIDENT = 'POST_PLANTFAULT_INCIDENT';
export const GET_INCIDENT_DATA = 'GET_INCIDENT_DATA';
export const GET_INCIDENT_DATA_BY_YEAR = 'GET_INCIDENT_DATA_BY_YEAR';

//Grid Failure
export const DELETE_GRID_FAILURE='DELETE_GRID_FAILURE';
export const GET_GRID_FAILURE='GET_GRID_FAILURE';
export const POST_GRID_FAILURE = 'POST_GRID_FAILURE';
export const SEARCH_GRID_FAILURE_DATA = 'SEARCH_GRID_FAILURE_DATA';
export const CLEAR_GRID_FAILURE = 'CLEAR_GRID_FAILURE';


//Plant Availability
export const GET_PLANT_AVALIABILITY = "GET_PLANT_AVALIABILITY";

//Plant Actual Generation
export const SEARCH_PLANTDAILY_GENERATION_DATA = "SEARCH_PLANTDAILY_GENERATION_DATA";
export const GET_PLANTDAILY_GEN = "GET_PLANTDAILY_GEN";
export const CLEAR_PLANTDAILY_GENERATION = "CLEAR_PLANTDAILY_GENERATION";
export const GET_PLANTDAILY_GEN_MONTHLY = "GET_PLANTDAILY_GEN_MONTHLY";
export const SEARCH_MFMDAILY_GENERATION_DATA = "SEARCH_MFMDAILY_GENERATION_DATA";
export const GET_MFMDAILY = "GET_MFMDAILY";
export const SEARCH_AMR_GENERATION_DATA = "SEARCH_AMR_GENERATION_DATA";
export const GET_AMR = "GET_AMR";
export const GET_MFMREADING = "GET_MFMREADING";
export const GET_AMR_METER = "GET_AMR_METER";
export const DELETE_ACTUAL_GENERATION = "DELETE_ACTUAL_GENERATION";

//JmrMeter Availability
export const GET_ALL_PLANTJMR = 'GET_ALL_PLANTJMR';
export const GET_PLANTJMR_BYID = 'GET_PLANTJMR_BYID';
export const GET_PLANT_BYJMRID = 'GET_PLANT_BYJMRID';
export const DELETE_PLANTJMR = 'DELET_PLANTJMR';
export const POST_PLANTJMR = 'POST_PLANTJMR';
export const CLEAR_JMRMETER = 'CLEAR_JMRMETER';
export const GET_JMR_METER = 'GET_JMR_METER';
export const SEARCH_JMR_METER_DATA = 'SEARCH_JMR_METER_DATA'; 

//Weather Station
export const POST_WEATHER_STATION = 'POST_WEATHER_STATION';
export const CLEAR_WEATHER_STATION = 'CLEAR_WEATHER_STATION';
export const GET_WEATHERSTATION_NAME = 'GET_WEATHERSTATION_NAME';
export const GET_WEATHER_STATION = 'GET_WEATHER_STATION';
export const SEARCH_WEATHER_STATION = 'SEARCH_WEATHER_STATION';
export const DELETE_WEATHER_STATION = 'DELETE_WEATHER_STATION';
export const GET_ALL_WEATHERSTATIONS = "GET_ALL_WEATHERSTATIONS";
export const GET_WEATHERSTATION_DETAILS = "GET_WEATHERSTATION_DETAILS";

//Module Cleaning
export const POST_MODULE_CLEANING = 'POST_MODULE_CLEANING';
export const CLEAR_MODULE_CLEANING = 'CLEAR_MODULE_CLEANING';
export const GET_MODULECLEANING_NAME = 'GET_MODULECLEANING_NAME';
export const GET_MODULE_CLEANING = 'GET_MODULE_CLEANING';
export const SEARCH_MODULE_CLEANING = 'SEARCH_MODULE_CLEANING';
export const DELETE_MODULE_CLEANING = 'DELETE_MODULE_CLEANING';
export const GET_MODULE_CLEANING_DATA = 'GET_MODULE_CLEANING_DATA';

//Water Consumption
export const GET_WATER_CONSUMPTION = 'GET_WATER_CONSUMPTION';
export const SEARCH_WATER_CONSUMPTION = 'SEARCH_WATER_CONSUMPTION';
export const CLEAR_WATER_CONSUMPTION = 'CLEAR_WATER_CONSUMPTION';

//Module Cleaning Analysis
export const GET_ALL_PLANTSBY_PLANTID = 'GET_ALL_PLANTSBY_PLANTID';
export const POST_MODULE_CLEANING_ANALYSIS = 'POST_MODULE_CLEANING_ANALYSIS';
export const GET_MODULE_CLEANING_ANALYSIS = 'GET_MODULE_CLEANING_ANALYSIS';
export const SEARCH_MODULE_CLEANING_ANALYSIS = 'SEARCH_MODULE_CLEANING_ANALYSIS';
export const DELETE_MODULE_CLEANING_ANALYSIS = 'DELETE_MODULE_CLEANING_ANALYSIS';
export const CLEAR_MODULE_CLEANING_ANALYSIS = 'CLEAR_MODULE_CLEANING_ANALYSIS';

//Plant Tilt
export const POST_PLANT_TILT = "POST_PLANT_TILT";
export const GET_ALL_PLANTS_BY_PLANTID = "GET_ALL_PLANTS_BY_PLANTID";
export const DELETE_PLANT_TILT = "DELETE_PLANT_TILT";
export const GET_ALL_TILTS_BY_PLANTID_DATE = "GET_ALL_TILTS_BY_PLANTID_DATE";

//Plant Generation
export const POST_PLANT_GENERATION = "POST_PLANT_GENERATION";


//Plant Tilt Schedule
export const POST_PLANT_TILT_SCHEDULE = "POST_PLANT_TILT_SCHEDULE";
export const GET_ALL_PLANT_TILT_SCHEDULE = "GET_ALL_PLANT_TILT_SCHEDULE";
export const DELETE_PLANT_TILT_SCHEDULE = "DELETE_PLANT_TILT_SCHEDULE";
export const GET_TILT_SCHEDULE_DATE_PLANTID = "GET_TILT_SCHEDULE_DATE_PLANTID";

//External Budjet
export const SEARCH_EXTERNAL_BUDJET ="SEARCH_EXTERNAL_BUDJET";
export const GET_EXTERNAL_BUDJET = "GET_EXTERNAL_BUDJET";
export const CLEAR_EXTERNAL_BUDJET = "CLEAR_EXTERNAL_BUDJET";
export const POST_EXTERNAL_BUDGET = "POST_EXTERNAL_BUDGET";
export const DELETE_EXTERNAL_BUDGET = "DELETE_EXTERNAL_BUDGET";

//Inverter Daily
export const POST_INVERTER_DAILY = 'POST_INVERTER_DAILY';
export const CLEAR_INVERTER_DAILY = 'CLEAR_INVERTER_DAILY';
export const GET_INVERTER_NAME = 'GET_INVERTER_NAME';
export const GET_INVERTER_DAILY = 'GET_INVERTER_DAILY';
export const SEARCH_INVERTER_DAILY = 'SEARCH_INVERTER_DAILY';
export const DELETE_INVERTER_DAILY = 'DELETE_INVERTER_DAILY';
export const GET_ALL_INVERTERS = "GET_ALL_INVERTERS";
//Missing Inverter
export const POST_MISSINGINVERTER_DAILY = 'POST_MISSINGINVERTER_DAILY';
export const CLEAR_MISSINGINVERTER_DAILY = 'CLEAR_MISSINGINVERTER_DAILY';
export const SEARCH_MISSINGINVERTER_DAILY = 'SEARCH_MISSINGINVERTER_DAILY';
export const GET_MISSINGINVERTER_DAILY = 'GET_MISSINGINVERTER_DAILY';
export const GET_INVERTER_DETAILS = "GET_INVERTER_DETAILS";

//Missing Weather
export const SEARCH_MISSINGWEATHER_STATION = 'SEARCH_MISSINGWEATHER_STATION';
export const GET_MISSINGWEATHER_STATION = 'GET_MISSINGWEATHER_STATION';
export const GET_MISSINGWEATHER = 'GET_MISSINGWEATHER';

//Task Statistics
export const GET_ALL_TASK_STATISTICS = 'GET_ALL_TASK_STATISTICS';

//GET_ALL_WATER_CONSUMPTION

export const GET_ALL_WATER_CONSUMPTION = 'GET_ALL_WATER_CONSUMPTION';
//GET_ALL_EXTERNAL_BUDGET

export const GET_ALL_EXTERNAL_BUDGET = 'GET_ALL_EXTERNAL_BUDGET';

//GET_ALL_AMR_Meter

export const GET_ALL_AMR_Meter= 'GET_ALL_AMR_Meter';

//GET_ALL_Penalty

export const GET_ALL_Penalty='GET_ALL_Penalty';
export const ADD_UPDATE_PENALTY = 'ADD_UPDATE_PENALTY';

//AOP Budget Details
export const GET_ALL_AOP_BUDGET_DETAILS = "GET_ALL_AOP_BUDGET_DETAILS";
export const POST_AOP_BUDGET_DETAILS = "POST_AOP_BUDGET_DETAILS";
export const GET_ALL_BUDGET_DETAILS = "GET_ALL_BUDGET_DETAILS";

//String Monitoring
export const GET_ALL_STRINGS_BY_SMU = "GET_ALL_STRINGS_BY_SMU";

//Strings
export const GET_STRINGS_BY_SMU_ID = "GET_STRINGS_BY_SMU_ID";
export const POST_STRING_NAME = "POST_STRING_NAME";
export const DELETE_STRING = "DELETE_STRING";

//SMU
export const GET_SMU_BY_SMU_ID = "GET_SMU_BY_SMU_ID";
export const GET_SMU_BY_INV_ID = "GET_SMU_BY_INV_ID";
export const POST_SMU = "POST_SMU";
export const DELETE_SMU = "DELETE_SMU";
export const GET_ALL_SMUS = "GET_ALL_SMUS";
//Dashboard
export const GET_ALL_PLANTS_WEATHERS = 'GET_ALL_PLANTS_WEATHERS';
export const ADD_WEATHER_INFO_BY_PLANTS = 'ADD_WEATHER_INFO_BY_PLANTS';
export const GET_DASHBOARD_ALL_PLANTS = 'GET_DASHBOARD_ALL_PLANTS';
export const GET_HUB_DASHBOARD_ALL_PLANTS = 'GET_HUB_DASHBOARD_ALL_PLANTS';
export const GET_CHARTS_INFO = 'GET_CHARTS_INFO';

//LenderDetails
export const POST_LENDERDETAILS = "POST_LENDERDETAILS";
export const GET_ALL_LENDER_DETAILS = "GET_ALL_LENDER_DETAILS";
export const DELETE_LENDERDETAILS = "DELETE_LENDERDETAILS";
export const GET_ALL_LENDER_DETAILS_BY_YEARPLANTIDS = "GET_ALL_LENDER_DETAILS_BY_YEARPLANTIDS";
export const GET_ALL_LENDER_DETAILS_BY_YEARMONTHPLANTID = "GET_ALL_LENDER_DETAILS_BY_YEARMONTHPLANTID";

//Preventinve Maintenance
export const GET_PM_TASKS_BY_ACTIVITY_ID = "GET_PM_TASKS_BY_ACTIVITY_ID";
export const SEARCH_PMUSERSTATUS_BY_ACTID_DATE_PLANTID = "SEARCH_PMUSERSTATUS_BY_ACTID_DATE_PLANTID";
export const GET_PMUSERSTATUS_BY_ACTID_DATE_PLANTID = "GET_PMUSERSTATUS_BY_ACTID_DATE_PLANTID";
export const GET_PM_REMARK_STATUS_BY_USER_STATUS_ID = "GET_PM_REMARK_STATUS_BY_USER_STATUS_ID";
export const GET_PM_TASK_GROUP_BY_PM_ACTIVITY_ID = "GET_PM_TASK_GROUP_BY_PM_ACTIVITY_ID";

//Performance Loss
export const GET_PERF_LOSS_PLANTIDS_DATE = "GET_PERF_LOSS_PLANTIDS_DATE";
export const POST_PERF_LOSS_DATA = "POST_PERF_LOSS_DATA";

//PenaltyColor
export const GET_ALL_PenaltyColor = "GET_ALL_PenaltyColor";
export const ADD_UPDATE_PENALTYCOLOR = "ADD_UPDATE_PENALTYCOLOR";

//SETTINGS

export const GET_GRAPHS_SETTINGS = "GET_GRAPHS_SETTINGS";
export const GET_PAGE_GROUP_SETTINGS = "GET_PAGE_GROUP_SETTINGS";
export const POST_PAGE_GROUP_DETAILS = "POST_PAGE_GROUP_DETAILS";
export const POST_USERS = 'POST_USERS';
export const GET_PAGES_SETTINGS = "GET_PAGES_SETTINGS";
export const GET_USER_MANAGEMENT_SETTINGS = "GET_USER_MANAGEMENT_SETTINGS";
export const GET_HUBS_SETTINGS = "GET_HUBS_SETTINGS";
export const GET_PROJECTS_SETTINGS = "GET_PROJECTS_SETTINGS";
export const GET_ALERTUSER_SETTINGS = "GET_ALERTUSER_SETTINGS";
export const GET_DD_ALERTUSER_SETTINGS = "GET_DD_ALERTUSER_SETTINGS";
export const GET_GRAPH_GROUPS_SETTINGS = "GET_GRAPH_GROUPS_SETTINGS";
export const GET_ERROR_CODES_SETTINGS = "GET_ERROR_CODES_SETTINGS";
export const GET_MOBILE_SETTINGS_SETTINGS = "GET_MOBILE_SETTINGS_SETTINGS";
export const GET_FORECASTCONFIGS_SETTINGS = "GET_FORECASTCONFIGS_SETTINGS";
export const GET_PR_USER_MANAGEMENT_SETTINGS = "GET_PR_USER_MANAGEMENT_SETTINGS";
export const GET_USER_ROLES_SETTINGS = "GET_USER_ROLES_SETTINGS";
export const SUBMITED_UI_SETTINGS="SUBMITED_UI_SETTINGS";
export const GET_MCleaning_SETTINGS="GET_MCleaning_SETTINGS";
export const GET_Cleaning_ALERT_SETTINGS = "GET_Cleaning_ALERT_SETTINGS";
export const GET_PAGE_NAME = "GET_PAGE_NAME";
export const GET_USER_MANAGEMENT = "GET_USER_MANAGEMENT";
export const GET_ROLE = "GET_ROLE";
export const GET_HUB = "GET_HUB";
export const GET_PROJECT = "GET_PROJECT";
export const GET_MOBILE_SETTINGS="GET_MOBILE_SETTINGS";
export const GET_INVERTER_CONFIGURATION="GET_INVERTER_CONFIGURATION";
export const GET_DATA="GET_DATA";
export const GET_WEATHER_DATA="GET_WEATHER_DATA";
export const CLEAR_PLANT_MAPPING = "CLEAR_PLANT_MAPPING";
export const POST_FORECAST_SETTING = "POST_FORECAST_SETTING";
export const GET_GRAPH_GROUP = "GET_GRAPH_GROUP";
export const POST_GRAPH_GROUP = "POST_GRAPH_GROUP";
export const DELETE_GRAPH_GROUP="DELETE_GRAPH_GROUP";
export const GET_ALERT_USER = "GET_ALERT_USER";
export const DELETE_ALERT_USER="DELETE_ALERT_USER";
export const DELETE_USER="DELETE_USER";
export const SELECT_ALERT_TYPE="SELECT_ALERT_TYPE";
export const DELETE_PLANT_MAPPING="DELETE_PLANT_MAPPING";
export const POST_WEATHER_CONFIGURATION="POST_WEATHER_CONFIGURATION";
export const POST_INVERTER_CONFIGURATION="POST_INVERTER_CONFIGURATION";
export const POST_INVERTER_MSVMAPPING="POST_INVERTER_MSVMAPPING";
export const POST_MFM_CONFIGURATION="POST_MFM_CONFIGURATION";
export const POST_INVERTER_CSVMAPPING="POST_INVERTER_CSVMAPPING";
export const POST_PLANT_MAPPING="POST_PLANT_MAPPING";
export const GET_FTP_DATA="GET_FTP_DATA";
export const GET_EDIT_ROLE_MANAGEMENT = "GET_EDIT_ROLE_MANAGEMENT";
export const GET_PR_ASSIGNMENT="GET_PR_ASSIGNMENT";
export const GET_CONFIG_ALERT_USER="GET_CONFIG_ALERT_USER";
export const GET_MODULE_CLEANING_ALERT="GET_MODULE_CLEANING_ALERT";
export const GET_PERF_ANALYSIS="GET_PERF_ANALYSIS";
export const GET_YVALUE_DETAILS = "GET_YVALUE_DETAILS";
export const POST_YVALUE_DETAILS = "POST_YVALUE_DETAILS";
export const GET_GRAPH_BY_PAGEID = "GET_GRAPH_BY_PAGEID";
export const POST_PAGE = "POST_PAGE";
export const POST_PAGE_GRAPH = "POST_PAGE_GRAPH";
export const DELETE_PAGE_GRAPH = "DELETE_PAGE_GRAPH";
export const POST_ROLE = "POST_ROLE";
export const GET_ALL_ADAPTERS = "GET_ALL_ADAPTERS";
export const POST_GRAPH = "POST_GRAPH";
export const GET_HUBUSERS = "GET_HUBUSERS";

//Field User Report
export const CLEAR_FIELDUSER_REPORT="CLEAR_FIELDUSER_REPORT";
export const GET_UNASSIGNED_TASKS="GET_UNASSIGNED_TASKS";
export const GET_UNASSIGNED_TASKS_PLANT="GET_UNASSIGNED_TASKS_PLANT";
export const GET_UNASSIGNED_TICKET="GET_UNASSIGNED_TICKET"
export const GET_HUB_TICKETS="GET_HUB_TICKETS";
export const SEARCH_HUB_TICKETS="SEARCH_HUB_TICKETS";
export const GET_HUB_TICKETS_DATE="GET_HUB_TICKETS_DATE";
export const SEARCH_USER_TICKETS="SEARCH_USER_TICKETS";
export const GET_USER_TICKETS_DATE="GET_USER_TICKETS_DATE";
export const SEARCH_HUB_PLANT="SEARCH_HUB_PLANT";
export const GET_HUB_PLANT_DATE = "GET_HUB_PLANT_DATE";
export const GET_HUB_PLANT_ID="GET_HUB_PLANT_ID";
export const GET_ALL_USER_TICKETS="GET_ALL_USER_TICKETS";
export const GET_USER_TICKETS_DATE_USER_ID="GET_USER_TICKETS_DATE_USER_ID";
export const GET_HUB_PLANTID_DATE="GET_HUB_PLANTID_DATE";
export const GET_USER_INFO_QUARTERLY = "GET_USER_INFO_QUARTERLY";
export const GET_USER_INFO_HALF_YEARLY = "GET_USER_INFO_HALF_YEARLY";
export const GET_USER_INFO_YEARLY = "GET_USER_INFO_YEARLY";
export const GET_PLANTS_BY_USER_ID = "GET_PLANTS_BY_USER_ID"
export const GET_MENU_PERMISSION_BY_ROLEID = "GET_MENU_PERMISSION_BY_ROLEID";
export const GET_USER_TICKET_DATE_USER_ID = "GET_USER_TICKET_DATE_USER_ID";
export const GET_LAT_LANG = "GET_LAT_LANG";

//pr request
export const GET_ALL_PR_REQUEST = "GET_ALL_PR_REQUEST"
export const GET_PR_REQUEST_ID = "GET_PR_REQUEST_ID"
export const POST_PR_REQUEST = "POST_PR_REQUEST"
export const GET_SELECTED_HUB = "GET_SELECTED_HUB";
export const GET_ALL_HUB = "GET_ALL_HUB";

//Report
export const GET_ALLGRAPH="GET_ALLGRAPH";
export const SEARCH_REPORT="SEARCH_REPORT";
export const GET_REPORT_DATA="GET_REPORT_DATA";
export const GET_REPORT_DEVIATION_DATA="GET_REPORT_DEVIATION_DATA";
export const GET_REPORT_DEVIATION_EXTDATA="GET_REPORT_DEVIATION_EXTDATA";
export const GET_REPORT_DEVIATION_EXTDATART="GET_REPORT_DEVIATION_EXTDATART";
export const GET_REPORT_DEVIATION_DATART="GET_REPORT_DEVIATION_DATART";
export const POST_FORECAST="POST_FORECAST";

//Forecast
export const GET_TIMESLOT="GET_TIMESLOT";
export const POST_TIME_SLOT="POST_TIME_SLOT";
export const DELETE_TIME_SLOT="DELETE_TIME_SLOT";
export const GET_FORMULAE="GET_FORMULAE";
export const CLEAR_FORECAST="CLEAR_FORECAST";
export const GET_FORECAST_DASHBOARD="GET_FORECAST_DASHBOARD";
export const GET_FORECAST_REPORT = "GET_FORECAST_REPORT";

//Analytics
export const GET_PAGE_DETAIL_AND_GRAPH_DETAIL = "GET_PAGE_DETAIL_AND_GRAPH_DETAIL"

//Performance Analysis
export const GET_PERFORMANCE_DAILY="GET_PERFORMANCE_DAILY";
export const GET_PERFORMANCE_MONTHLY="GET_PERFORMANCE_MONTHLY";

export const GET_PERFORMANCE_ANALYSIS="GET_PERFORMANCE_ANALYSIS";

export const GET_PAGENAME_LIST = "GET_PAGENAME_LIST";

export const GET_GAUGE_REPORT_RESPONSE='GET_GAUGE_REPORT_RESPONSE';
export const GET_GAUGE_MONTHLY_REPORT_RESPONSE='GET_GAUGE_MONTHLY_REPORT_RESPONSE';
export const GET_COMPMODL_GAUGE_MONTHLY_REPORT_RESPONSE='GET_COMPMODL_GAUGE_MONTHLY_REPORT_RESPONSE';

//Email Template
export const GET_EMAIL_TEMPLATE_BY_ID = "GET_EMAIL_TEMPLATE_BY_ID";

//Analytics - Graph
export const GET_GRAPH_ANALYTICS="GET_GRAPH_ANALYTICS"

//Rooftop
export const GET_GRAPH_ROOFTOP_RT="GET_GRAPH_ROOFTOP_RT"
export const GET_ROOFTOP_DASHBOARD_REPORT_RESPONSE = 'GET_ROOFTOP_DASHBOARD_REPORT_RESPONSE';
export const GET_ROOFTOP_REPORT_RESPONSE = 'GET_ROOFTOP_REPORT_RESPONSE';
export const GET_INVENTER_COMPARISON_REPORT_RESPONSE = 'GET_INVENTER_COMPARISON_REPORT_RESPONSE';
export const GET_GRAPH_ROOFTOP_RoofTop="GET_GRAPH_ROOFTOP_RoofTop";
export const CLEAR_GRAPH_RESPONSE='CLEAR_GRAPH_RESPONSE';
export const GET_GAUGE_REPORT_RESPONSE_RTDASHBOARD="GET_GAUGE_REPORT_RESPONSE_RTDASHBOARD";

//Userplant
export const GET_USER_PLANT = "GET_USER_PLANT";